version: "3.3"

services:
  ol-db:
    container_name: gen_alg_db
    image: bitnami/mariadb:10.10.2
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ol
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user123
    ports:
      - "3306:3306"
    volumes:
      - keycloak-postgres:/var/lib/mysql
    networks:
      internal:

volumes:
  keycloak-postgres:

networks:
  internal: