spring:
  datasource:
    url: jdbc:h2:mem:gen-db
    username: root
    password: root
    driverClassName: org.h2.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
